<a href="https://colab.research.google.com/github/guptatanmay1998/Word-Embeddings/blob/main/tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


In [3]:
print(tf.__version__)

2.5.0


In [5]:
x=tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [7]:
x=tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
x=tf.ones((4,4))
print(x)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)


In [9]:
x=tf.zeros((4,4))
print(x)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)


In [11]:
x=tf.eye(4)
print(x)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [12]:
x=tf.random.normal((3,3))
print(x)

tf.Tensor(
[[-0.7654272  -0.7372763  -2.0232673 ]
 [ 0.6131971   0.17988512  0.24897143]
 [-1.2131255   0.10579549 -0.81710607]], shape=(3, 3), dtype=float32)


In [14]:
x=tf.random.uniform((3,3))
print(x)

tf.Tensor(
[[0.94142103 0.5653151  0.5995687 ]
 [0.9429616  0.64402235 0.77851987]
 [0.43538177 0.40842164 0.9375142 ]], shape=(3, 3), dtype=float32)


In [16]:
x=tf.range(start=1,limit=10,delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [31]:
x=tf.constant([[1,2,3]])
y=tf.constant([[7],[8],[9]])
z=tf.add(x,y)
z=x*y
z=x/y
z=x-y
z=x**y
z=tf.matmul(x,y)
z=tf.tensordot(x,y,axes=1)
z=x@y
print(z)

tf.Tensor([[50]], shape=(1, 1), dtype=int32)


In [47]:
x=tf.constant([0,1,2,3,4,5,6,7,8])
print(x[:])
print(x[1:])
print(x[1:8:2])
print(x[::2])
print(x[::-1])
indices=tf.constant([0,2])
x_ind=tf.gather(x,indices)
print(x_ind)
x=tf.constant([[1,2],[3,4],[5,6]])
print(x[0:2,:])
x=tf.range(9)
x=tf.reshape(x,(3,3))
x=tf.transpose(x)
print(x)


tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)
tf.Tensor([1 3 5 7], shape=(4,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([8 7 6 5 4 3 2 1 0], shape=(9,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
